---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-postgres
  namespace: storage
spec:
  encryptedData:
    POSTGRES_BACKUP_ACCESS_KEY: AgB5/y9sKEZjOBd1dxlESsV0D0CDY0ZPwj3+wfHtkApFrBh8p0PHfMu8BUbD2eAXf1TBXKb21puoY7Oh09F/HNOL7+ZtkqTtMGCk9r6l6FXl6MmZ+d910/MI3JTtfRBbpsKtSKqCgXusZWf0XdAtJ1O9x20H3WMDFzQHGYgcRwR4jQbpFdDF0u2htSoG2M/GnYMFg8+7DP+2QNFdhd+VGS7OQsa9wjziDGVGIKlG8VO9qQmhkAOrfAjcZXUDNJRpjeI4wxdFckeQwcDexqqAqND7jXH2beLCCAoHf43EdmuGtxfhpNkVBxlLm6DFe8hOYr6TbwsZJaS8OQwor3qjKQ+UeWCt51WCjY9k9FHvYll1J5YZBgSpaf+wCrSR4JRFfsveWVHpwZ6fDXJ2OboDO+OqnHdiEYM0FCTKwbvlFmTaoJj07tNOl9d4WGKqgy+u8hVdi83ce/0vRFH/UuCJojQcxJG6S4bsKWkcBgRzk7CjQo7lnqBrx4tdtPnVzCYTSZBULuGnwL+eZ3FP2PsmEcV90nr8QQm7qKVcRo+0oyqC9PrN5o/IVsRRQyQI/zhbckpphnIID3qaHJiKjv0HJktRvcfXutJmPwyo5Ei21IYKw5BiIOcOccYuru3tnm8L2KseOdbvv6imrNEij++cnG0+dGDCJTo3lYhB8YhFDOn/EGCGLcWJjtNHPWwAzr2fyTardwM9qA8c7a/hazdrP0M=
    POSTGRES_BACKUP_SECRET_KEY: AgBcLUDnj9tWs1m1DypKZXsx8mzfdLYx6AwTcj2YEWJcxe+MoZog7Z+boNZ0LK0OATKxzToX76J/UhDoWsoM14ZkQbY5BP/8JldyNEqNW03Fvp8CEgQvR3M6pE+wfyckA/U2P6E3rkDWxSqi4Y/errXbH1fmHLw5E2PX+bOwV3oY8kQktXiSwdphpIvY3jsbtxK9Jq37+T+Td7BaZuE99ZBTNzUR+WSVYQ3uhq7rLfpgS0KeQUSc3Jch9mCbajcIfFJexKO1YTZs1ky9hXJFaWavyfgmGfHw2kgRj90+UoPQa+VaNTkzGwA+u5hrC6474dl363+g2/iSC1ZAJK4YH5lHvzayJZaFnOlyDJjgDo0MFSsnHedd3bc4fnxgvXWLvS6wrYlrt3J+tWElNP1zkrQ02yATjjnzExXvZVlg36KoJ2nsehPQn8B2QjKJbDHsg01ZBPM59/FGgRE9ZbR+tlXEm3/87oVN2ICaA2LrdU2PMdwSXVgUniSZqAXlgAN4lOdtRAaIjHn2xWFVT3wBmBKjAOdMpph2qRsM6EVODqtzvQC82k+jYMMXJz3GcxUW9sS+tAvzF5I1tT4WHaR/Dzt79NG9xqOdmP25fPYnMG8CrvvT7qirBB2GMLuhp4uLkq0P6+seIcZS4yfv4m9L1uz+oqyMMmA+Gmh+4H5mzclAuvz2QLPHaee7obafdybQew3tqLUWuBELQTnDXwIAN/XAXpK6leSSUQA=
  template:
    metadata:
      name: minio-creds-postgres
      namespace: storage
