---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-mimir
  namespace: storage
spec:
  encryptedData:
    MIMIR_ACCESS_KEY: AgABnYwhfXWLtPeDEy0nsuHNulDppiyXQK2j/3FezCAIGFqxcFY7xB8e8P1E6okwfH+ZhjkNXwvr5retWC1jEBAlo37H83LWlMc2hBKtqjnJLjtnoxgGBkOhIQykrm4m6QPQLWpslkOH0OwDh89x8kU6JQJEylQ9/31TUT6W4ooWdu3OVerbWtTMO6uNBMfrpLMby1LOkA8J+80US0TJpLj4rvAKyx8JuhkKkhNcCKdD0jeVFM/NWh0+MZ2wpM5O5bYcF0+A7I0eX4pe8voqqBChIwljgOZI0NeHy/jWf0KGAqOnzuLb+cb1A2zzXSauhMC7EwGizpykjhuyQKLQTsPpm+uQMY+AxzYW4w7WOZL0H5kU5pSAWK0WFHb8yCzhLjMalrYDpfzUDHGAMPqWyvzaqlFQGxQo7V80LYe3tDr1HEbbpgXiewRQeIEQlfvYxFdPccNg4GZGwzUGj7n8SGBK4b1gV+2bn96zEAEQCcIjb9Qh02NQJfnWGzQa8U0LaXIguzfbYMmO5cZLEcrEDo6WdcpXaW0RZif+Ifi4ZxS9oMl3B7QU0NMAzJ7lQiMil1XOym1OL8mOCbbbjtLTFttuDKlhTJLQQRWvuhx++fXw8oGucaYLIcLlRRAheajyjX/BSGU5DFoqxSYC8nBJPNAI4XSZCSkBMoJv3pq1wzL+VK1paf3n5pPXzfRVNWJSnVXT7LEpJA==
    MIMIR_SECRET_KEY: AgCfBKuvdkdiWbZgOq3coWKQ9iGL0F3eLqFYx1DwsftHBmgdcopGSkGBwPz9gr0CslME08htZBVG6O8ey5Mg0Y/p8+gmbEMx9MJmjV94zDdz+ooSN80BuO0//MMP2KRObyMlqYks8yPN6PGRYsWwV4V5wIujIBTBZxJ6vpLln+Qkfh4gIqojapy9Z+sp9juQvlT00TUXYCHxRVnoYyW5CNTUY8a+zCUJaxNvoK37Qv5ZMuToX630WM8op8rCNdkd+bPK+Hl+WQocrhLqGFprkd0JiMUd6eneTAyIoal5qYYzsqO0rSovaUQNjW+s6XuC+txDMA3YhxUnI1caKeA8DCVWVm2zNowFjT2a8X1FGyLdIJj0PrJCcMHJanJzU+P2sm+0N76VgTwk59gkRZ5pa6cLzV4JhtnLpu24qjPZDetEuIf8tTmP15ngoL7cKq+/4mruq+QbR596R1Ps9U1AdZJDjliE0pIp8enUEoTdOG9J+oNaKU/UYu+OhAs84/SiUBqLlWOZQ5XmqkQFT7ifnhkvWvAenkIGbpA054YyRv9RF5dNF5AcpSfHvuhvDeUnSGnMuGyzG2QiiwFIEA5w9EKoax0206rzYOzKT3/OskQqp3necRcZ3D+1+azSOThSoqcmoBpdmRMa9IDcs4PNu/WfZOJIgWigkyYxV9J0JEirkLbxgGiHahtwcN1qzgmLtsEOGfxsbTnmY2rAMsSrXZVZcW25LBJswng=
  template:
    metadata:
      name: minio-creds-mimir
      namespace: storage
