---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-loki
  namespace: storage
spec:
  encryptedData:
    LOKI_ACCESS_KEY: AgBHG/wkpB9d8N0PVBeXI51AJ4ngCo/kTMNbiu14+mq1AlfFQhj6JfdUEFGDauI2TFd9TIUPevA6BTJjsV4iPDtPyUZ5yGz55XtY4DfEpptlMYGM7Vtc/jl54/O93UeYrHn14XgaNL2ktpX1T19RTJSAenqQcK18e4pFYUVfhLp+eylcJqdZiTeI4gbhXlsfpEaJMiX1+KuecmYTxU5GVL0WovByYCylpblW5qHqECLP7Qvf61Tw6F5NurekFSdj49lCLXce93sr9YcVetArubPPUyvQmnKJIWuG45m2+4fuvME0Zn1Vdx5XqqkvPR/9U8lErqJLYfQmnAlJNiSNJsZzLwi6wqwwmUVsb8sWJXwpnFprfAIWQC/e740R4CiX9EZ5e/ItRi2vEg69Z7/uRj+dwK1Z+UQqgr02TrUKFzVigy9v7QUEnr/xV1rs/f1SqIZApbohzfRSfHKHFEmwQB4MUhoUYWt5qqLsPM3boRs/KY6AaTQxM35fBpkvreFJvdzecc3Ny7/DeK6BRgFTQuHhUVwqlyf/pisnWvZJtrFaikT5S0z1v9VZEMsGDwAPdzALnkIM2FMhlnY4yLNDPg6TbU91ZjzweIVcMy7IkFXXCbgYkiRF49uirzzY9tGOCIwJIVJEVo27ho5sj1rOwSoLeILaCd1gMI89yfQq9oQCwlnoDtUzWs0MLYUG9NI+h7w4MFpD
    LOKI_SECRET_KEY: AgAB0/HAwAvfS6tQlqz6VPtGSgw8WY6w8C/KizbT3nzqTafd80LvSlzzKlRP9RE3kr/5Pllxln9VMok2qqffoAe9z69mZToQRmK5G5BXD6Kbqcpw+olDxAJmnaqKVuw3z2smpWSp97hDMeapgFwjsWt4rjEvXXih2AN3jyZ9pSpgPNApu/cVWzeCE37E5SrC/nFxg0daaATwKitMuYjvhoN7e0ZKj9Yv/m0i+z7yI+17bVdYnEk6Iv209FIqPk6H9fJM7oQYNCdez366s8tAq0A9WOxwagztpB1ufGVW0XsqPmR55DiiJH+6dKs/PhCTpzDKpKm6JIB8XajqP/hNTvqZoSeoASSfO5DuLgaoNO9SfOsm9rCd4V3BVfsvoTsA0DJpPzp98QRDDMzfekMKXm3lmh7ilmlJVO3X3/aHllsBTNAYCEk2XUMeVc7viG3Y9B0yDJuTyH6rbN5OWREJBymnkd+PJyNf8nR4TM3uJGRakTakmCRlQrbYIeXry79mlGRusSKrBNsOixEzGI1b0KXWIwcFOeo6642P+qo4aaxx9SnSafqry66pT81WuyL8wEMeJjc6DVihBX2uBd853e4ayOj8gH8rkQYFtUPSxq5tSfeKIaTcU/jE/R+xQo+qMhdA+n8CzUvwmlZ29WwNr/LWGSNIS8AMmlsAahppyuvw4IgOH02qDUYhMYzGSaxxgCRh1r/PF/lRzDoYfrSdIsLZjW7tI6Y7PMU=
  template:
    metadata:
      name: minio-creds-loki
      namespace: storage
