---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: storage
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgA/jDSdw6bQg3qFNlRFtKQoJUGWHswivwLjW2StDa/4h+nbk3EgzZW3pofkmBIvZ7ko40ZcTakklAAMPs89DOu9FiiLSSn0kQ3viHJOHWsXmH4fzCmgU+ew9rtYuH1GfZ4MvVRuXtRlCLzbgie27PGqNJSqbWfWrujwzIdBzNUTJ3a8qHENWXep7TiaoeWiEwiPhGqIkZUjsX8hJS7ry88fZnzjzrnzRnpQNEMs+NWzO0Skzg7OTC+bEx7a+6AfrkuNsETskX7W/k8FgOVoObibphQusTPNCEwo9QFxfO0+avuuYmA5uKAHe+frxypmRiQ5DRNb6ZstWcf3qiTy6kYF+nVCWuUJCQd6mcmnAL4BNwQdgkoEpWFDl8FZr0WSjO0A760CepiTlaTnmRE2n6aqjFLjZQ7cUQaNneGOponDb0JBiWdveKLk/AVxgCgDe+5tSYWY6SiT5czKiOi/t/a2TkREV2+gJZTliqV7WlwdqzRpd3VBb4a1NHNCaTM92ciPe8445tLtb/0cF0ALHfq6xgzcZDE/VxRPv60AuATvqIS8mikXIiMVHFPO7pbx/a/b8wIb9NW6mA/RoS6FLYWhOIadfWOKL/1LAnEajI6T5XLP9HaY5Xxjao9fDr0NZgqpweKq1u8VIcd9H6neNgvXYYCpe/fZPfe7jUkIn9nVyuPTca+uRBLhr0pHCaZGdGFVYWteuGP8/GlewI/EAilOiU3g6SOft18=
    MINIO_ROOT_USER: AgALSNX7CwkdgLlT074wLoEI2TSn7noXSHJdsEB+yXZkZz0SJ4Rdl5B2BxiSl1pHPYhWCAELXP9Om/Tx3LFpaOWtUO6Zr8wBL9YxfaLxSeeUIJtd5IbDRsmtN1XnBidZG3LtvZIjpZTS0/Xgn4oHnBgbNeH94lq7a9xfcSk3I/xw1yRStiyLaCKw2zq+T+M1n/ywwxfvHl6aFX2x5hqay+P613OUkbge7GVDDq53mZj1zzFpPvN8trM8GWx3bMGVaMnhWfIBzyQvk5K+wjz4xuklGwsZmpdpXVKbsaEDTPZ0Mkli6BNcDrnvT0fUq6kKxGFBxHd38siXQmcjgX5fWTZaGAsSXGE9f0ctirBrNuTwpvRQ5ORnZTJ1em2S5/OtJUKlD/wLYmSSFhU//TEi6lxQ7eaexwdwAL2+Th/6KcAxrxw9DuMYbN0H82JXs+lKqeD8ZdHCwWTe+d+a0+QiqLNllmJekGBysyhiRSIZDiCCfNFqhXYSO7+zlNLtZbNoMtqbDOn1jxJhE+uudxTIP6M9efXFjwr0CrNgtL80OPPpddu6m7gfHUDkjZ8s2fGhmO7GjoqTl6wDAetRCbRDjSFxtBh1xWG7IxYwDnV+9LA66i3eiiWp2UPfo7Tp+wnOCT7OMnPn8tG0oGdhBD91qg8AVMRONdcEe++fSbWaFOvS3PBX8kkKYgl+8uVxJgKF43GzgP6X/9AhNOE=
  template:
    metadata:
      name: minio-credentials
      namespace: storage
