---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-postgres
  namespace: data
spec:
  encryptedData:
    POSTGRES_BACKUP_ACCESS_KEY: AgAD2Kl7VXHYyrSVrSbD+u8iZRFVebtjMKE4h7JB5b5Rovo6TLlmbwvKsdd9OIPjnmtSqdDNtefdWbbU0v63lBvDLJLKZZLyzsGT1fVQUL9FrYBrjYIVtlKkLTEXxkwzEgp2dDT7ar2kcmpEHrfACuCC3ZFwu0DGvFy4JN2noGqc46c2/ujo6D8MncfXZK+CrOJQX7RCHo1a4FgmM1v1ey5rxwZe8tIkv1ml2rmtURNRI06eu/0txhX7KuxWDp9cPywTSYNi/NrM3NgBlqdgSfEj9NSfhuktT4TYogF6yPmVz/ZhaXBRp2GQjnzG8JE7naS4CdhO4komyBiz5vkzhXHFMGRVKMHbgL53bgD4NwYimEr02JesRMjvTTbAY3GSB9A4zZzPRaBR+57L5/4wHDmy+5N68YzrmBhncHFV/Mpjv1tkeDvE89QsYJ/mK1Y6iWjxW0X4vyB+LfwWgS2v3mdDPmWyGbmvYd7BJpDNenOtxYvUjNnuQ28oJ35qtQvTm6edpw9YaZTj6k+RpejaQIw9tYbsh3VBmNid9q+WKy0+my6QCiyXCliePUp5BdcJvsVuGsB2tti+xRSpVfLL9thkmNEBRB3si8dLBv6GP3km8iB1jYaX+7pHCvuhT4F5KatrV01DGVqHhzTfyIIC8ZAI/24syM64LserClAX0EhBO5/v8urWi0Mu8J6589xL50LQgEVtshaOBw1x5ruuys8=
    POSTGRES_BACKUP_SECRET_KEY: AgBAMY1tXFBwGBB2AhVDzn+l14eoSnD7DcCSsv4LPFMGpPQl/NwEc3jAY6SZVjhe0h0UNjM8Hmx+6y7ds5/47ifDZ1Sy9jMxjGcU1ID2z3M21WQFdN7h7GbDA2WWsXszVh0Db5ZewoOBn33/uBt3gVwQ+ONTy9n1jaH+9oUpl3/siU0a5iTXf4W2HQPnbN/74GZWuKjt83JInMEyAPYhB85HAfBBfN0FB+6EEopKZdFeUHl/h0X/cMEnuXKBZHYP/+H1zq7Rnj2oxhwo7TGkccIWJn19vaUEwIFStuSzXerAJKwuQ9Dzq1XAYKVchAhIBUPGnvF/rGi2Yui9Nqj9qZ4PIB++zQcO3WrVUK82VwLqWFnonoqfi3XKNHFpxMQ2VrqwGzv9a0Fz+OHOodgcTQHnMr6qyDBxt6qAkidK81ETPiXnzHLkAvb80Jg3H2lUtoLogrHYIo9yxAy0q4K3MBlYqG0WHDt32KttKBCli1NEsZn9x/+9TmjCSMJB8jEBd9CtBDXtVqy6cqijpLYi3j+F+BKV52wsi64MIzSIEni8epxwLaZ3fdFLA+/A6CFGGCEB74g6uIiD8F3AleHKWTMYUXGOm8r3w3W0piqPtghhjJXKZuYjS7Bi/ew2JHs85XH75LDAm7w+GKDGFj0+q8ePdmok/pgV8JvQ57c9UghCt37EblkeG9XS/LM2ulZl1c2vsJIKA/N3gPcU9iuoBbVp6ysdbTDsVog=
  template:
    metadata:
      name: minio-creds-postgres
      namespace: data
