---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-app
  namespace: storage
spec:
  encryptedData:
    APP_ACCESS_KEY: AgDAJxdb6ljpRe/rUSXCJPDV4bEmwPjSleZcRRSO0kEHrRC70Hjo4FSeTSCpb4HskZZP0fUrrmkLVt2xeodRtQONb/CvWsr5F8bwM1XuJhqeywGydyaUlc6AYWKLvU1nggBGDW2AwlF4QdhulHxgh8e1qqWWaBpXDBbjPCE6HJS7B6YyCqO9A7amHkLQDh5AO146p7J9fKbKpMbFNMVsIkAfsriXQloeJgnjcLUW9ogUQJLT0eMymWJFaMLtjCWGfDKLw0WLK9gu6irnxByq09TyxNdWlFh9AGiTMzRQn4NHQxLaG1z2qANEkhBvFl73eFJe/z4OzPaqYlufbr5thfY3kB0b6ytrikILgKuvfAiMXVpP4XFF0CG3/Fzw0NfLj/FIYudEm+D1rkaHL5RYEeTP8C/gYi3TYQQEUFMbRq/9PZY1n3ypC5xtlSTmYKS2TNpXvrqArx2ShQCEAkijBHn7358oM6mtWw8p2zqU3kAVWeOE38OdF/TlLk4TUyOvqiUok2PX5zUO7c1kxtLQ4+RE8C69V4ay3vIGhyM2sIG3XjQt9jZtFJG5+TNEqliwmj7L7Lvi88DUPouIlqVkuiJfc3UHdg9UQmIGJriD0GUi4hm1CCh/vfAPFl0HYYIQl5mJzDSYbVJs5AxeUMS0/FJaMH+MNTKpAXJayqjJtAOTBeENIqsn6IRRWmayqvVDSAwVyks=
    APP_SECRET_KEY: AgCcHvQCts45/5X4NY5/UFz7b6yUYe/+aTXmFhRGmJyMmK8GzsLueBUysA6ewOMxz0LrtezI8jj/J4pR6k9i40WAFoMaVTfnCycIxhPGewnSZj4tmg/Wo5210M5BGS796X1CaStY/8RMMuXf6VzhD4z7MoaCioji+D6jc5I/7/Rp1kMRi28HzVeH1wLkqPnQ6I73W6Bvt819j/OKBLAmxY17w2TMeuaYRHPvqasOt7fofs7yEX9OPGX1p+hoOQHE2vqwB/ilO8ZGrZSczU5MUhYUueVDJ9/AxMg0eU3Xsx5T2kiL3ZywOMzDIqHQqWohoW/hg39dlg/1wS/LCUb7+MnxDTJ3r2OluX0ckyI/mciJduf794zpUGo0dQwfcnEqaeYZeoAMuqELzPGmZ+0+5nA3SGKEUlIzTGXc7UQNc8CjVcK9CNsEKjpDkWVN7RoP7l0pxyr5etoQoDU8rKFp79axEbD3zKgFIT6jf6gV10s75sn75Q8QIkx8UcIJB1PELABSkCgAeONlQePqSvSo/HsmKIw+RpSbAbIXr9qv4zBP+oXlx6YnpR9BN/vFH2OL1mUDigigmQeqOG/tkbrkRxcWk8oxpAGIGBKTTS4RZb+B693Gdrd4ZEMyd4PLFvlynae059hpFfJpR+TgXyAjo0ZOLSS2bVoXnf69kg7L9PtagSdUsXezsE9okrb+xUeX8YGhT4u1yQnCendbubxi36oQv/I0KjET+88=
  template:
    metadata:
      name: minio-creds-app
      namespace: storage
