---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-tempo
  namespace: storage
spec:
  encryptedData:
    TEMPO_ACCESS_KEY: AgAKKx3rqZ7CTpBMktQQxZp81IozVJzLDMm40pQf08zycdcQ3x8zoodkB9U8rnTm36f/zxJnAuEKlFC3daID2UB9CyAd04JmGwOcObFiz1jAhupPnW5gCtcwKS7906MYvEjsAUJ11BSZ6goeNkcHAhxe5KU0BRjK46bA+v1H1WyVRs+xeDH5IP+6kLmWOS0KtIaMVvaDnNzt8DykZD1Bw9lH/L8Pz4SUD7SfZZ1ai6rFhtZT89HyD01nU/6cyWQfrHnXL5QQyZF+xbrG+w+4jkbEFHpesoY2bSBfyytn6RVil4R7NvKgZ1FHeGm/GQYCe56wYsE1F81WehdcxWvp7luvnYcdtFD2NaBvAiFfcTiKfjsux8VWpuwg+n0HaVT2VobyrMXwvwpgVTFms49bnFub/bvNbYXSIpUH/oa43g/MAfxx/WichZe3F19T3V2xJZPCXJjICE6dJrnp9DfccZB/Td4SjK+v5vu7aF8Ub+FfWWIaSF8PEbinvqkks5tITeiiJ+iwgv5yT+jUnBskSi2CnTczUwu9h8Zn/frwL181GcJKak0J4KTt/QnAYsMTlIjeDA7VKyUInKB2gIF9T3ayF5VnDrmpzr3T5wdAmBXrCKviGghdiE0EaAt6jDOZvQqzKifq54UaDzkmKw4J4S4SpAxlbe2jx/8PwrKBQz7i6r6qPffcLXeyqYlJWPiKPGHU0bY8DQ==
    TEMPO_SECRET_KEY: AgCO4ny3LTho3I4dPfZUrr0Nm/bUOa4mK2kyI9u7XFarCerdoF5fCtRlxyvfXqX2N8Oj5Pu4sUlp2PYB54kC+vcgVgvYcfGEcKtpH6wgWjIMj5v1QICpX9QzdqHxI6a119P/g1GhW5jmHkwnQB8c+SC1JH8ySv+Jcitgzg3qJzwHHSQlCAr9cl1KLSDDFUWPj68kVdBWgUpis7ynfJZs6HA2x6BrC0JfujWT1DalicDvAwLNxN03sZOaUtL9UGAa5vgBAS5AxdE03T1HfUC881AZWr10Acdo9gfDPYinHYRFNqyGDob87opaUpXRh8rE98rJ0n/3BkJ69PrCNliyjvwbf6vr+cJYrS5WtkQzfVLFCwc3NE4QDu5Mk7UdVm45WggBWYG6urgH69EdoIVPvYy/+914vXQSGcuB/o19C4wz1W1jBFwOoI9R5c1CI+0i9s9Z5Bwnx5Z8ly9kR8zmOI9z1H132ygwi2gCqJ7cmLDn7T63W/1Q4P+T0Ovwi5znPlCdowE60wGjaQTHeSQ3CYMtwVcaLIQVAw1k0oQjHQqG4FeO5iom78wDnld56DWWT5pXPb+CsmNiTCpRkT2YoFreQ0AWLUvgtlPzQNjwM+ckXuGatvvbLyHHPztQIJvalS8coF/r0e0SvcS3OIdMM0E6wpFMdxBJkkz7vI9pJ60oFJ8o1FBWwydKO9uJc5G2qW/QWYTagT5g9TQnWkPVQFUIDNFyEHFnlW8=
  template:
    metadata:
      name: minio-creds-tempo
      namespace: storage
