---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: data
spec:
  encryptedData:
    password: AgB93QIhJy0nMsgeN6R5kNCGgoM8OKSdTq8O2jfUD9KZ4VphKQZgYBLDj7qxRux3cDUGujwTnB2UfMHeUu2Fs4EPLLQwpFVA66ETHyDeEtrfV+P7N9luH/1zHKXnxAPs9tE8eN2ZHOHwC+wrh0O4OWSlxFsp/MnBv7bVTApsYWpvS4Yj2Swjlal58eRja/vVl8hVqV7+kC6F2xJlmPfNA1+uf031aTUe+u17GAGHYHf5VRizSfNpj8cqGiUe+xYSaY3WbLwBRAuUEPuYamsNMDTtCNNae7ss0Ozf9x+ViwyEqnXvwmDaawsSAgnIqXBQhYKQHLxsS5PRZ49rv+MMlFUfCEbF6KXlOj4NFcdLfHpUiiz7dc38Z/lBn4jYCu68us0RR+qcyyIsaeHIlm+7DB3EYKD3o0TZ8ZdiyNgJBpiL0/M9ZmyVUnevJRxLWlqQSS87Rkw2UzklDorL6u8dMDXl7Vl/6CNJrJQzYZRVkeE2MnVFXlZgWKnfXq7kzH1AEuLZFQkn/OOsG0x+2A73MdEkPkxG3Y2rpH/xZGzS6ILhVtCuL9YS1eD25uJmN8HwTLReqUqcv7tECPR/vR5TYIpQB8F5mkWr2XAJmyvWxFqO3UGR/r1C8z/aqR4sVFKaOY5dDk6V0NPrURfq4o0Bho5ChJwn6OKyvO2nnrIJSQ4NyJ6ZiIoILoCj6KIjz7sJUYZpkTpOtZQ9rkMiNpGkZritqoV5oC/xK+8=
    username: AgAM1XaroGOgZhRH2XrzUv5ZKJzoWpJLGF7ymJbIO13Oi0Z1HVKIkF29roJEcD1frBEO+o2/BNEYX+kZQKo+IkL7+o/GCVJzKaWl321JKLjiPbhpoyotq8fXIR6CFqIfgzE+O5OqrD59ieN6JcJfRlAAK6otBqSw1mfOK2QZiwk1O2jcX9qQGcn7UVFDz4zuhSwHSvgaaT6tM9dmOe3xllNaPbEl7Vkzkf7HkCIYSfeOpePUiuTyYdhydo7MHYKaqyp4kaCuqkjJYLBkdzhr1lMl7/TrvEs7QW4NdE+wFiDm5+SNJl7rTV3QkOb2GijyZiDBj/23MXBVg0XmW02BV+KqEiWoi1483wT8hpmcGi4YOcFlEEbJsCtjGGaPkklyPmI5+zSGfWFZfc0TD8gSNhdMBgwMhd4EM36OFqfrzbfVBAMohn9oaVjMSCNkXoMNr5DKlHktyYQOF5m9v7ILI2GkI5PuieivEEZypzHnGsBy9rbIUg2MAtJ+V6azVKA/d5VWBk9Q2jxPGWzBESWw8PxGDJFcu1AVGoGf2jFGUId9oQEWnBMtM7dMMa4jNMupzmkbPBR+4h1xklpJwlsHRW7E04aTdzZwl4319V26zwSWbTYaReGErnXIBXwF7EsdtUQ6TUy0daKz7EOzHmXf2zk6NbxFzWySq+DWrJEIY/MgSL30kFRjxmpbMkdZAc6oeIqb8io=
  template:
    metadata:
      name: postgres-credentials
      namespace: data
    type: kubernetes.io/basic-auth
