---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: valkey-credentials
  namespace: data
spec:
  encryptedData:
    VALKEY_PASSWORD: AgDAdOK8T1+Rx65EjebmSsLP7O6kz0AeWnq2AjAF4hjOz3YqVLFGEfPBqenQb2Hd0b7KHbeW3G+oxSkiH09/cGm0Vf69xWkZixiAvoAv2616YkrlZ0fReKcNJP8VDP7WL6oeIKcFj3lpBBjA7cVz79Ux70Qyk5N21JFSxz/6GdTDCl9dCrMdpXrdhD0yXEZFPMh+e3dUq1OsL8EP9VypfCPXKnayQ7uOwdo7ivIyjgAANf3fHXMmCKDAS3Z3zUPCBHqmqRlQCtnP+4BVDQZWrlMJGI7H9zOkcLHSWECpO1UT0XQNJkpkcAe4O0gPjwWJYnpOxTXvqKm/VcvdmwTBL4QfJ7V2mkhbPmO9tNoHpiHQt66Cpr8xzSiJGCRuB1Nlqgj+8m36bliZaswQZ/jmokRmLnF6XkM5Swa3s+w9t/HmqlbklGolp4x4dw4gfIqqIH6nmfWIp8/IBRn+kayuFJ2nGBUDxvRLCoJ9UeI6eWq4L/aVI6pCryMM5o68OHYPwQS6wMJaUrRnzFjIQ0m4IEIQqmx64vK4OuDL0HPu8IKgcfXnjYbhp3rXjYYRyJQav+JviVJ7hjHZ6J/l1GUxAgpfeInJU0rqyfPtZsL7COBIPIAc/sRH70vZqGnnnuYHEztaoWPSTGXr5CmDWEXLOnVLrBSwkoob3j+jXHyNtsrc+qSvx6neO+uLnRrrEvrW4h1sKZNL3KeHpZhO1zrXFR6I9+Cp1m+/+lk=
  template:
    metadata:
      name: valkey-credentials
      namespace: data
