# Copia da credencial provisionada em plataforma-gitops (namespace storage),
# reselada para o namespace observability -- mesmo padrao usado para
# minio-creds-postgres-data-ns.yaml (D8 de plataforma-gitops): o valor NAO
# foi regenerado, so extraido ao vivo do Secret ja em uso e reselado para o
# namespace onde o consumidor desta change roda.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-loki
  namespace: observability
spec:
  encryptedData:
    LOKI_ACCESS_KEY: AgBUscc/yir8Bn4s3KqTy4tN9GkcoVb9Tq753RKcBILMyUveMlGmqyAfy0oevx5msKQi0wxP4oSdyBAW0L30E8oddrL/4yjYTT+HEGbYsq3biQcvuPrbAt5yUdSUAk2X6goHyURvK1Fxy01SojD9RX4KUguqjRkgYwR+wMnUU2eoYLL9h8XwZ7iB2Ji8KRbjIqW3DjbFxh2lANNzd/qp7eqP7+N+wukQCBsuRD8nyyYhGNBx1uTuVxn/EIXbJbzy3TVpyjbc94PJkfE+rFlOZwZcbeU0X+Ro7niYlmduUPY+IpSi63Z2YM9cckMHrZ8srC5rJK/a8bBKKMIthhyk++nYHg3K/bWXCyNdgwjzgiJh/6h8Ewy8PLZc00kdPx8/bsuK2r8FmLdW7kaKYXK3spbQtYPBR1oaqdqYgVlOyCPMI4lrnupaqwsr3rAELO/zdcEpNfHCTajfcB+lg1s1edV0grzWhow4QkdaeSRzkTfqonBMpv/AGo+b/ycrI2eWzTf/nR0qn0Z1g66RswehELD5+FW4ZL1i89Iyi9gqOmQudY4ejaKl/wLBXp0z/PFcfaUCX0umiUD3KsD5gFnkgIOe0rdjtb90tcHrzIUxhICihnO6NIGaaxfxRR0FL5ZucA+fml9D0+SCfVa0BxBndUmUFVDOP/DEmA9nWI13dNev1HOgJdwEG7m2WGcG2dxiBjkduXyD
    LOKI_SECRET_KEY: AgCMYdtthNVULnzdo/Uj9LOHJpGXO64+fYTY0Tjoxg7owPp8fDVsK58QTK6rmXl4QPol5IUlztnu+lMadLe1U8mwDaVxFxH3Tb5n5cHDNN9WIPPYLZWYUdAuGPphoYZk1xX/jUnicj+Og5aaVwuau5ZIrqXr7nPret7e9Ob1bzkjecuESSG/Cf/Dpr4GSsCrm3MTLxOgbn9HSf/JCzktllptFZHd3OWtwokW3hPrHVlH628e/gVKqGDrTxv/MzyuHtbwlAvLEEb3p7NsmsMSFQThAUBaQemNTXe2QUglX2AuQa0hQd58NUQ134fOAcCYq9hktvJTKaQ4QIsERHP9RNigK0ocEx1v/1U642lJgtx4AeXXWa9NBhmkxfmMixYsk9meWNpYan32h4+LWL7QLHwt855zQxRgc/iAo12y3DH7K26yULqBx6pHBclz2RI9YvYG/j4VYKmrECItH/1kPqO5h833el/VXBF3cFxOkVYNeB/h7+a/2mdanAUosYxx9+wNay2eu3zc33OJDfWaW6zIu8+MdwGQk70W9vgmpiwMBcLb27SV3DVSLSb9lzHOAs2oBqX5CfNfrqL30XmaJ1iT1cTsQeU5funl6BEuA33FI+kQRXrhk5GS8Fq3JeM1fOw8RF/bX2bxcgX9/DLHYokYciNqAFVdiv1zYINtxte0IAl6QOMgMzxBGPPgGnOnsEHDkzIJHTWAEiqNrrWZt4y797n1MVQyi+c=
  template:
    metadata:
      name: minio-creds-loki
      namespace: observability
