# Copia da credencial provisionada em plataforma-gitops (namespace storage),
# reselada para o namespace observability -- mesmo padrao usado para
# minio-creds-postgres-data-ns.yaml (D8 de plataforma-gitops): o valor NAO
# foi regenerado, so extraido ao vivo do Secret ja em uso e reselado para o
# namespace onde o consumidor desta change roda.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-tempo
  namespace: observability
spec:
  encryptedData:
    TEMPO_ACCESS_KEY: AgBPVUMdO7BdAmiFWQ3doM/gTQ6mLSr3SRZTRNcYXz5kgDSD9FIHuMDS76GZhD+827e6KMHFV6CF24mBfwysGqAuZe62ZEnT+SxZgSiYYhWde6QtQl7xp+OlDM+0DiFgVr+h3dJ6dpbwGwUyZgdarqIlnUrYmILXN8lSkQdgoSkdgZ6LjQh94ZbGHp7WRtcQ6clJLV9gsyhjjLoPuAIlOu2QyOBwTphet3Xz+dALkX/cC2vq5byFPfA2VPoKPeeGALDpgmjjRCur2gD2Zi5rOo8nlJLiz+BQU6b7jedbB2opdAYUpikIeyGmdPVhgjLt93t56hELlzLrTmGEOnqGI/YOMfrNMQUDUb/qPjISQvnlVe1AkEmK93VsIC/UMNqFsK6PYEogvMyiKRkGpOKmR/DPR6GYFLLSXjZD1LcFyjFwLlUXtlo9lBb/MlhUP+McxLKuwU2snbJnUbUS/O9Ym4q0/LK1xBLS5LrzFfFeQ6t1Osp5nLDkEooSD3VmRXxeFMRd1eTAb8Ws9CG1FAIQAUByebsgl9FQ5Z+ZcFax14vIji64Br52Pyf0D6v18a+R+n2r43rI1dOBBfEcN0b6b342lU3jn0OhLirHwa9UYxwQ2Vluk8IJR7NN3C260vO7yIXn3ZvMmB9wDkQYl1yzbPuxN/zThc8my+/Ty8acF3LKWOvBPEeRwLMt7WevZISeQMlHkZdOUg==
    TEMPO_SECRET_KEY: AgBY8F2prYMopxshEBPZKybH7NGwKLybCYoJgGtj5F9y3RCxJto5T8pPj8fsZQW3aqO0vVfFhyf7eBPwOFldZfWguPdyumzbakyTYOhvyXiVA68+NHFnAhjsxiqof1Ikup+WUjPncJrtGMa0CphT8JyrPWyjEMk7gSK3m4iFI4pcPgzB83H3UVCE6OFSZz+Qve+DSwCfGtYdFO96WkTBkUoDnhWtfMeuCqVZx9zopTfb+aDuw41wdquRW/IokiFtw+0sz1d9/Vta4NdKe0XX6mB5PiUhDn9uHhBkv8eRIceCnsPLdHlhXs4ZmY6s+A2bRVFRyWi8hsfWwfHNNUYz/rrTarAD01hFKAdKlHj9NbxOlNr/EP5F6qJs6h/UUMrM1hFD169IpUWXAormIS0OY6FzzdlSvoCh136GKSAXNt6VEhjEhRJOo0DZ60bRDl0nSdP/9PSg3c+3Pk/ziutNijCFhw33rgtHnFnl5/y/t/B8aO+zScPiMf+lYwZCEtwBBgesFBUJaWnG9+hgpFj1/ADs8NAKxj/VSk84EqVm5yq7yEG2SxYrvbBGCcEdO2oDH+u81ucDD6xGVdSgZi27pow2+b5z0FajZSXEuWUlvrQ3Y84STYm6/ZZ5UB2PyKXnACgcuiiNSzt9x016iqPIZCNhRzq4OVPTXkmlwek0uNgm1mxQx06uK/tMPJxI+mKorw7jMbid1qZhlrTdTYR6hcTiQ4QMJjX2QJM=
  template:
    metadata:
      name: minio-creds-tempo
      namespace: observability
