# Copia da credencial provisionada em plataforma-gitops (namespace storage),
# reselada para o namespace observability -- mesmo padrao usado para
# minio-creds-postgres-data-ns.yaml (D8 de plataforma-gitops): o valor NAO
# foi regenerado, so extraido ao vivo do Secret ja em uso e reselado para o
# namespace onde o consumidor desta change roda.
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds-mimir
  namespace: observability
spec:
  encryptedData:
    MIMIR_ACCESS_KEY: AgAQlfI7EnFA7wi6uD9PfRo7bPKXjdM6QlCiJsDx+FOaudToNpk+qDFcP28ev8OHq3I23ihJrk0QzzIWQa0q6UU3rqdZp69GmVhuT+gOjQOkuEfmuA42dmSbmlrttKyYdtphVJH75pfA9U6vvfm1xI9JpQEGS8iVxhZPQuvm9E2P8I/n3lWVQT/FBKN23OKPxhsODSIBPVAdMMexjbCKHa0r1R5pMGn8hj4EDxlnAv4TlWHd2Gp7TIGH/sliWYwYBn6t/e5iPxcGfyY5kUUxz3ROojQvOz2D5uoZ0/UbmgyGkyfudFb/4EQnxof6BuR3SZcpU6XwxRTVf+YmAv1IiTnIJ7EZHhbGWTI1lwdgGPjEDyGWbk4d7hDvRBkFxcwwO+5txtE8txFUfB396XcDc/+1gUzPZ6J3yASUq0jCwbVh9ahJJGjCxjpBdF9n11sG7EUSCcZrnvK07ev4sk1nx3MoF8sWA0dsS0sglarulTWZJGrGvMd2j6pQDKiY4nUM/TYRz7Xonl/fS/GPWvFcCv1pdf9HrIoE+BnysiPjJLtRGCI7nrgUnjNF5GHPqomRlue3dHTfxh84wlyP4niye367OvTu7NTTc9zRiNpxna5VTce1su+ls6f6pXoTIJ9pflAR3lnjEMGTcmHxznLCbGlgUnGsjwRRUDhtTbaOuHurfFjBdBmbmZA0CUTIzxnnenKRNtVc5g==
    MIMIR_SECRET_KEY: AgDBH0/7LsKuN5nnd12YxBZVuu6APOs9aV4aHl+lrFLb7X3unKbjN+C/5KpKBdBhPlF7SXKBX70qZMWrMz539LDrYtj8+xoMvHZ+UFSFmaSwoxXcnphYhtgpa8ew8xARl3QyC/M+lUXGzWHcfYV1K+plX3RUAItEDT/IIJCp5YYC1fcjzjaslq8JunbPCEOv7rZ0RVY9kgVqgTCfxg+TPlGRHgkL6L9V3vN+2rZ01cu4Rvl17zNd+p91h/gjMdGNIfF5praaBFjvnLQShp34nsz7TxTUNKuGazhrKlTwvUZOcTYpM4Pr4ghCLra5RqOOcUQ3/cTv9ItdvFNCv+oDgl6dDRD46jSn8XtxebhfemyICgu/ATr14W0FqM8OUD5iIvzA7cN5ODtWJqdRqPzQuCM6IzpAAq/ZFpLA8+rqTzXgjEUeRj9LnqEsp1OtEcznd4dYzooNce0bH+JedNcc8UYN97IaB3XAL/YG2XGCOCbeHfcEuRvy4uNKxT0/KHR9Xdti2gBWzh+ymjKtfkZtkcfDZgZubCR78h8hEeLH39YQjWzCU9piQ8LnzXau8LK+MF4MHtZ8uhKHzdVp300Kuro6+JD9pDkvEYjPe0/6r9WnCeRnUHwxneaZszo4QbpDlLTrCm8G1gn8mSw5LQ7Y8yIOha5J7+8Ess6NcEHppZX+A2uYYjJwWC4DZdcJcD3udKm5gJU9T1YsDKkHe6LRhrh1ViTPMeyMGyU=
  template:
    metadata:
      name: minio-creds-mimir
      namespace: observability
